spring.application.name=LearningRestAPIs

#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/learningRestApiDB
spring.datasource.username=sunilrawat
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=false

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.servlet.context-path=/api

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:modules/patient/data.sql





